
production:
  # Paths and URls
  PATH_UPLOADS:   "/home/production/railsapp/storage/"
  ASSETS_HOST:    "http://assets.novacurriculos.com.br"
  UPLOAD_HOST:    "http://cdn1.novacurriculos.com.br/"

  # Configuration mail
  ADDRESS:    "smtp.gmail.com"
  PORT:       "587"
  DOMAIN:     'gmail.com'
  USER_NAME:  ''
  PASSWORD:   ''

# development:
#   #PATH_UPLOADS: "/home/picolo/ruby/nova_curriculos/public/"
#   ASSETS_HOST: "http://localhost:3000"
#
# test:
#   #PATH_UPLOADS: "/home/picolo/ruby/nova_curriculos/public/"
#   ASSETS_HOST: "http://localhost:3000"
