development: &dev
  adapter: mysql2
  encoding: utf8
  database: nc_dev
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: mysql2
  encoding: utf8
  database: nc_test
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *dev
