production:
  ADDRESS: smtp.gmail.com
  PORT: 587
  DOMAIN: gmail.com
  USER_NAME: luizpicolo
  PASSWORD: *picolo153

development:
  ADDRESS: smtp.gmail.com
  PORT: 587
  DOMAIN: gmail.com
  USER_NAME: luizpicolo
  PASSWORD: *picolo153

test:
  ADDRESS: localhost
  PORT: 1025
  DOMAIN: localhost:3000
