development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/pedido/efetuado"
  email: luizpicolo@gmail.com

test:
  <<: *development

production:
  authenticity_token: F0F299EF843240ABB14A9A484FEE7972
  email: luizpicolo@ibest.com.br
  return_to: "http://app.novacurriculos.com.br/pedido/efetuado"
