# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:logfile: /home/production/railsapp/shared/log/sidekiq.log
:pidfile: /home/production/railsapp/shared/pids/sidekiq.pid
:concurrency: 25
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30
:queues:
  - [carrierwave, 7]
  - [default, 5]
